trigger:
  - main # Or specify the branch you want to trigger the pipeline on

pool:
  vmImage: 'ubuntu-latest' # You can choose a different image if needed

steps:
  - script: echo 'Hello, world!' # Replace this with your build and test steps

  # You can add more steps for building your code, running tests, etc.
  # ... previous steps ...

  - script: |
      npm install -g snyk
      snyk auth login
      snyk test --all-projects
    displayName: 'Snyk Vulnerability Scan'
